const uint8_t IN1 = 3;
const uint8_t IN2 = 5;
const uint8_t IN3 = 9;
const uint8_t IN4 = 10;
const uint8_t PIN_IN = 4;
const uint8_t PIN_OUT = 2;
const char CARACTERE_INICIO = ':';
const char CARACTERE_SEPARA = ' ';
const char CARACTERE_FINAL = '\n';
